# Generated by Django 5.2.7 on 2025-11-05 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('estado_intercambio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionChat',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='core.chat')),
            ],
            options={
                'unique_together': {('chat', 'evaluador')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.chat')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, help_text='Nombre público opcional', max_length=15, null=True)),
                ('nombre', models.CharField(default='Sin nombre', max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto', models.URLField(blank=True, null=True)),
                ('habilidades_ofrecidas', models.TextField(blank=True, null=True)),
                ('habilidades_buscadas', models.TextField(blank=True, null=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('habilidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('nuevo_chat', 'Nuevo chat'), ('nuevo_mensaje', 'Nuevo mensaje'), ('intercambio_completado', 'Intercambio completado'), ('calificacion_recibida', 'Calificación recibida')], default='nuevo_mensaje', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.calificacionchat')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.chat')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.publicacion')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.publicacion'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aceptado'), (2, 'Rechazado')], default=0)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_moderados', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='ChatParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('autor', 'Autor'), ('receptor', 'Receptor')], default='receptor', max_length=20)),
                ('calificado', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.chat')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chat', 'estudiante')},
            },
        ),
    ]
